name: true_vpn
description: True VPN Client
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ✅ ФИКС (главное)
  slang: 3.31.0
  slang_flutter: 3.31.0

  # ✅ ДОБАВИЛ ДЛЯ HWID
  device_info_plus: ^10.1.0

  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.4
  rxdart: ^0.28.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  shared_preferences: ^2.5.2
  dio: ^5.4.1
  dio_smart_retry: ^7.0.1

  yaml: ^3.1.2
  convert: ^3.1.1

  crypto: ^3.0.3
  path_provider: ^2.1.1
  path: ^1.9.0

  loggy: ^2.0.3
  flutter_loggy: ^2.0.2

  uuid: ^4.3.3
  url_launcher: ^6.2.5

  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0

  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  slang_build_runner: 3.31.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/world_map.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
